{
  "id": 70,
  "repo": "vector",
  "issue_url": "https://github.com/vectordotdev/vector/issues/5511",
  "pr_url": "https://github.com/vectordotdev/vector/pull/5529",
  "issue_description": "Ping @leebenson \r\n\r\nHey,  noticed that `vector top` was not working on master today and a couple of tests are failing.  It renders and the components are listed but there's no metrics.   I was trying to figure out what was going on but no luck \ud83d\ude1e  so I thought I'd report it.  Would be interested to know what the issue was.\r\n\r\n<img width=\"989\" alt=\"Screen Shot 2020-12-11 at 5 04 31 PM\" src=\"https://user-images.githubusercontent.com/4615775/101965749-f97fb800-3bd2-11eb-930d-6c5517164ed0.png\">\r\n\r\n\r\nI would verify all this, but I rolled back a few commits and this **did work** locally:\r\nhttps://github.com/timberio/vector/commit/feb0c0e7c6f9c21b4d1021076d9fec651ceba200\r\n\r\nAnd the next commit **did not work**:\r\nhttps://github.com/timberio/vector/commit/f38fb43999a5bb0896ac55c8f901d70db3af0ab8\r\n\r\nThat was this PR: https://github.com/timberio/vector/pull/5346\r\n\r\nTest output:\r\n```\r\nrunning 14 tests\r\ntest tests::api_graphql_component_links ... ok\r\ntest tests::api_graphql_health ... ok\r\ntest tests::api_graphql_meta_version_string ... ok\r\ntest tests::api_graphql_event_processed_total_metrics ... ok\r\ntest tests::api_health ... ok\r\ntest tests::api_playground_disabled ... ok\r\ntest tests::api_playground_enabled ... ok\r\ntest tests::api_graphql_component_added_subscription ... ok\r\ntest tests::api_graphql_component_removed_subscription ... ok\r\ntest tests::api_graphql_component_processed_bytes_totals ... FAILED\r\ntest tests::api_graphql_combined_heartbeat_uptime ... ok\r\ntest tests::api_graphql_component_processed_events_totals ... FAILED\r\ntest tests::api_graphql_heartbeat ... ok\r\ntest tests::api_graphql_uptime_metrics ... ok\r\n\r\nfailures:\r\n\r\n---- tests::api_graphql_component_processed_bytes_totals stdout ----\r\nthread 'tests::api_graphql_component_processed_bytes_totals' panicked at 'Test failed', tests/support/mod.rs:419:17\r\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\r\n\r\nrunning 1 test\r\n{\"timestamp\":\"Dec 11 15:57:28.057\",\"level\":\"INFO\",\"message\":\"Running healthchecks.\",\"target\":\"vector::topology\"}\r\n{\"timestamp\":\"Dec 11 15:57:28.058\",\"level\":\"INFO\",\"message\":\"Starting source.\",\"name\":\"\\\"processed_bytes_total_batch_source\\\"\",\"target\":\"vector::topology\"}\r\n{\"timestamp\":\"Dec 11 15:57:28.058\",\"level\":\"INFO\",\"message\":\"Healthcheck: Passed.\",\"target\":\"vector::topology::builder\"}\r\n{\"timestamp\":\"Dec 11 15:57:28.058\",\"level\":\"INFO\",\"message\":\"Starting sink.\",\"name\":\"\\\"processed_bytes_total_batch_sink\\\"\",\"target\":\"vector::topology\"}\r\ndata: []\r\nthread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', tests/api.rs:507:28\r\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\r\n\r\n---- tests::api_graphql_component_processed_events_totals stdout ----\r\nthread 'tests::api_graphql_component_processed_events_totals' panicked at 'Test failed', tests/support/mod.rs:419:17\r\n\r\nrunning 1 test\r\n{\"timestamp\":\"Dec 11 15:57:28.044\",\"level\":\"INFO\",\"message\":\"Running healthchecks.\",\"target\":\"vector::topology\"}\r\n{\"timestamp\":\"Dec 11 15:57:28.045\",\"level\":\"INFO\",\"message\":\"Healthcheck: Passed.\",\"target\":\"vector::topology::builder\"}\r\n{\"timestamp\":\"Dec 11 15:57:28.045\",\"level\":\"INFO\",\"message\":\"Starting source.\",\"name\":\"\\\"processed_events_total_batch_source\\\"\",\"target\":\"vector::topology\"}\r\n{\"timestamp\":\"Dec 11 15:57:28.046\",\"level\":\"INFO\",\"message\":\"Starting sink.\",\"name\":\"\\\"processed_events_total_batch_sink\\\"\",\"target\":\"vector::topology\"}\r\nthread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', tests/api.rs:459:28\r\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\r\n\r\n\r\nfailures:\r\n    tests::api_graphql_component_processed_bytes_totals\r\n    tests::api_graphql_component_processed_events_totals\r\n\r\ntest result: FAILED. 12 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out\r\n\r\nerror: test failed, to rerun pass '--test api'\r\n```",
  "files_changed": [
    {
      "filename": "src/trace.rs",
      "status": "modified",
      "patch": "@@ -124,6 +124,16 @@ impl<F: Subscriber + 'static> Subscriber for BroadcastSubscriber<F> {\n     fn register_callsite(&self, meta: &'static Metadata<'static>) -> Interest {\n         self.formatter.register_callsite(meta)\n     }\n+\n+    #[inline]\n+    fn max_level_hint(&self) -> Option<tracing::level_filters::LevelFilter> {\n+        self.formatter.max_level_hint()\n+    }\n+\n+    #[inline]\n+    unsafe fn downcast_raw(&self, id: std::any::TypeId) -> Option<*const ()> {\n+        self.formatter.downcast_raw(id)\n+    }\n }\n \n impl From<&tracing::Event<'_>> for Event {"
    }
  ],
  "fix_category": NaN,
  "root_cause_category": NaN,
  "root_cause_subcategory": "Not \u2018flaky\u2019"
}